
* Training From The Back Of The Room
  VER: http://brainscience.me/

* Clase 1 7/04
  + Introduccion a Nahual
  + Armar entre todos definicion de "calidad"
  + Probar Celfar V1
  + Conclusiones
  + Intro al ciclo de desarrollo de software
* Clase 2 14/04
  + Revision del ciclo de desarrollo de software
  + Intro de casos de prueba
  + Probar Celfar V2 y V3 (mejorando el reporte con cosas como "resultado esperado", "resultado obtenido")
* Clase 3 21/04 Casos de Prueba
** Conexion: encontrar las diferencias y anotarlas (NO en la hoja de las diferencias)
   + como hicieron para anotar las diferencias?
   + si le paso la hoja de un grupo a otro, puede encontrar las diferencias claramente?
   + objetivo :: importancia de la claridad al reportar algo. (lo que es claro para uno puede no serlo para otro)
** Concepto
   Explicar casos de prueba. Basado en lo que vimos la clases pasadas (grafico de desarrollo de software y sus
   actores) ubicar en que parte del ciclo aparecen los casos de prueba y a partir de ahi preguntar que entiende
   el grupo que pueden contener (id, nombre, pasos + data, resultado esperado)
** Practica
   Hacer los casos de prueba de Celfar
** Conclusion
   Charlar sobre los casos que hicieron y tratar de formalizar con algunos ejemplos bien armados

* Clase 4 5/05 Reporte de Bugs
** Conexion: continuar el dibujo (arranca uno, dibuja una figura y se la pasa al proximo, con 2min de limite)
   + que creen que nos muestra este ejercicio?
     - seguramente vamos a trabajar en equipos
     - entender que los problemas van a surgir, pero tenemos que recuperarnos
     - nuestro trabajo lo va a continuar otra persona, ayudemosla
** Concepto
   Explicar reportes de error. Hablar con los alumnos sobre que cosas no pueden faltar en un reporte de error.
   Anotar la estructura y contar que luego vamos a hacer los reportes con una herramienta (Mantis).
** Practica
   + Leer entre todos la especificacion de El Provinciano y tratar de entenderla.
   + Armar CP sobre El Provinciano.
** Conclusion
   Contar los casos que hicieron y corregirlos.
   Si llegamos con el tiempo, que los ejecuten y si hay errores que los reporten con lo que vimos.
* Clase 5 12/05 Repasando Casos de Prueba
  Hicieron CP de El Provinciano? Si los hicieron, revisarlos.
  Si no, dejarles tiempo para que los hagan.
** Concepto: casos positivos y negativos
   CP + y CP -, que les sugieren? Escucharon algo en las clases pasadas? Que creen que son?
** Practica
   Dar 5 minutos para clasificar los CP que armaron. 
   Pasar al pizarron y pegarlos donde correspondan. Discutir.
** Concepto: clases de equivalencia, logica?
   Si hago casos de prueba para ver info de las provincias de cada region... cuantos CP deberia armar?
   + Salta (norte)
   + Buenos Aires (centro, pampeana)
   + Misiones (mesopotamia)
   + Santa Cruz (patagonia)
   + La Pampa (pampeana) NOOOOO (aca caigo en la clase de equivalencia de Buenos Aires)

* TODO Clase 6 19/05
** repasar clases de equivalencia y logica


* DONE hablarle (por mail) a las 3 personas de Github@Nahual para que acepten los PR 
  le mande mail a jplagostena
* TODO ofrecerle a Denu pasar las asistencias
* TODO preguntarle a Denu si estan en el grupo la mujer con numero raro y otros mas de esa clase al final

* TODO hacer libro pdf pocket 
* TODO reordenar los temas del libro acorde al itinerario de clases
