#+TODO: TODO(t) IN-PROGRESS(p) WAIT(w) | DONE(d) CANCELLED(c)
#+FILETAGS: :notas:emacs:

* Cosas para hacer
** DONE cardiologo 10:30am
   DEADLINE: <2018-01-05 vie>

* NOTAS
** tmux                                                       :tmux:terminal:
   Los clientes (terminales) se conectan a las sessions. Pueden ser mas de una conectadas al mismo session.
   Cada session tiene una o mas windows, y cada window tiene uno o mas panes (sub-terminales). 
   Los windows pueden estar linkeados con mas de una session (pueden ser compartidos entre sessions).

   - tmux new[-session] -s session_name [-d] :: creates a new tmux session named session_name, detached if -d option.
   - tmux attach[-session] -t session_name :: attaches to an existing tmux session named session_name
   - tmux detach (prefix + d) :: detach the currently attached session 
   - tmux switch -t session_name :: switches to an existing session named session_name
   - tmux list-sessions :: lists existing tmux sessions
   - tmux list-clients :: lista los clientes (terminales) conectados a alguna session
*** Some tmux bindings
   - C-b d :: desconecta la sesion actual
   - C-b : :: abre la consola para poner comandos dentro de tmux
   - C-b , :: rename window
   - C-b $ :: rename session
*** Helpful tmux commands
   - tmux list-keys :: list out every bound key and the tmux command it runs
   - tmux list-commands :: lists out every tmux command and its arguments
   - tmux info :: lists out every session, window, pane, its pid, etc. 
   - tmux source-file ~/.tmux.conf :: reloads the current tmux configuration (based on a default tmux config)

** [[file:notas-linux.org][COMANDOS GNU/LINUX]]                                              :comandos:
