* About this Book
** Why is this topic important?
   As trainers and teachers, the single most challenging thing for us to do is to step aside and allow learners to learn.
   Engage learners from the moment they walk into the room until the moment they leave.
** What can you achieve with this book?
   Change the traditional and *ineffective* "trainers talk; learners listen" to "when *learners* talk and teach, they learn".

* Foreword
  Whats wrong with conventional training? It's just like school.
  In the workplace, teamwork is esteemed. In school, learning with others is called cheating.
  + Encourage discovery and coloring outside the lines.
  + Provide opportunities to experiment, and don't punish "failures".
  + Enable people to learn from one another.
  + Provide challenges to groups, not individuals.
  + Make time and room for conversation whith peers
  + Provide resources for people to learn things for themselves
  + Give workers the freedom to learn.

* What's In It For You?

** CONNECTIONS
   When you allow learners to teach each other, and learn from each other, they increase their own confidence, competence and ability to use -and master- what they have learned.
*** What's in it for you?
    TODO 
** CONCEPTS
*** Fab Four
    1. Decrease the time you spend talking and increase the time learners spend learning.
    2. Observe increased learner-retention of important information through learner demonstrations and a variety of easy evaluation strategies.
    3. Deliver training in a variety of ways that will increase learner involvement, interest and motivation.
    4. Increase your own energy and enthusiasm before, during and after training, so that it becomes an exiting process for you as well as your learners.



