* About this Book
** Why is this topic important?
   As trainers and teachers, the single most challenging thing for us to do is to step aside and allow learners to learn.
   Engage learners from the moment they walk into the room until the moment they leave.
** What can you achieve with this book?
   Change the traditional and *ineffective* "trainers talk; learners listen" to "when *learners* talk and teach, they learn".

* Foreword
  Whats wrong with conventional training? It's just like school.
  In the workplace, teamwork is esteemed. In school, learning with others is called cheating.
  + Encourage discovery and coloring outside the lines.
  + Provide opportunities to experiment, and don't punish "failures".
  + Enable people to learn from one another.
  + Provide challenges to groups, not individuals.
  + Make time and room for conversation whith peers
  + Provide resources for people to learn things for themselves
  + Give workers the freedom to learn.

* What's In It For You?

** CONNECTIONS
   When you allow learners to teach each other, and learn from each other, they increase their own confidence, competence and ability to use -and master- what they have learned.
*** What's in it for you?
    Todo
** CONCEPTS
*** Fab Four
    1. Decrease the time you spend talking and increase the time learners spend learning.
    2. Observe increased learner-retention of important information through learner demonstrations and a variety of easy evaluation strategies.
    3. Deliver training in a variety of ways that will increase learner involvement, interest and motivation.
    4. Increase your own energy and enthusiasm before, during and after training, so that it becomes an exiting process for you as well as your learners.

* Brain-Friendly Training

** CONNECTIONS
   One-Minute Connection: Fast Pass
   1. The human brain learns best when information presented to it is *both emotional and rational*
   2. For the human brain, paying attention is most often *an unconscious choice*
   3. Attention increases when the learning environment *changes*, and decreases when the environment *doesn't change*.
   4. *Shorter* segments of instruction are better than *longer* ones.
   5. Humans remember more *when they figure things out for themselves*.
   6. For optimal learning, the physical body needs to be *active* while the brain/mind is engaged.

*** Imagine that...

    | Program 1                                          | Program 2                                  |
    |----------------------------------------------------+--------------------------------------------|
    | trainer in front of the class                      | trainer walks around the room              |
    | reading things of the screen                       | engaging participants                      |
    | pause occassionally                                | pause often                                |
    | "did you all understand that?" no responses, go on | short quick activities                     |
    | tables in log rows, facing the teacher             | round tables, participants face each other |
    | blank walls                                        | colorfull charts everywhere                |
    | ordinary training                                  | interesting training                       |

** CONCEPTS

*** From Boring to Beneficial
    Regardles of a person's age, culture, race or gender, the human brain _loves_ to learn. It's a mean, lean, thinking machine, if you will, always in the prowl for new things to explore, think about, make sense of, experience and use. Its reason for existing is to learn, and it's genetically programmed to learn.
    The brain grows new connections, called dendrites, between neurons, or brain cells, when it is actively engaged in learning.
    Brain friendly training is about designing and delivering instruction in ways that the human brain learns best. It will include joy, accomplishment, desire, need, choice, active participation, and informal surroundings. 
    1. Positive emotional experiences.
    2. Multi-sensory stimulation and novelty.
    3. Instructional variety and choices.
    4. Active participation and collaboration.
    5. Informal learning environments.

*** Positive Emotional Experiences
**** The Choice is Yours
     1. Trainer A. "Welcome. Please take a few moments to introduce yourself to the people at your table and let them know why you are here today, and what you want to learn from this class."
     2. Trainer A. "Let's begin by brainstorming at least a half-dozen facts you already know about this topi."
     3. Trainer A. "That's an interesting answer to the question. In addition, you might consider this answer as well...".
     4. Trainer A. "Together, before the class ends, let's make a list of all the new facts you know about this topic."
     Trainer A's class is *colaborative, participatory and inclusive* - in other words, braind friendly.

*** Multi-Sensory Stimulation and Novelty: Timing and Movement
    Add physical movement (learner's movement, not yours), and the body _and_ mind become stimulated.
    Toss in timing -physical movement that learners participate in about every ten to twenty minutes- and learners themselves see a dramatic change in they own energy and interest, as well as recall and retention. 
    The simple act of standing after sitting awhile increases blood flow, and therefore oxygen, to the brain. A simple change in posture can lead to a profound change in learning.
    
*** Instructional Variety and Choices: Reaching most of the Learners Most of the Time
    Adding a variety of instructional strategies to the mix is another way to increase learner's attention to and retention of important content.
    1. Hand over a specific part of the training for them to lead.

*** Active Participation and Collaboration: Stepping Aside While Letting Them Learn
    As trainers, we need to give learners just enough information to start, then step aside while they learn from using the information in some fashion.
    
*** Informal Learning Environments: "Do Not Touch" Versus "Make Yourself at Home"

    | tratitional                  | informal                                               |
    |------------------------------+--------------------------------------------------------|
    | desks in row, facing one way | round tables, or desks in circled clusters             |
    | be quiet, don't move around  | move around, talk, converse, and learn from each other |
    | dry ambient                  | posters on wall, music                                 |

** CONCRETE PRACTICE

*** Simple Steps
    + Change the room environment :: rearange things to make it friendly, informal, and inviting. Add music, colors, and a welcome sign at the entrance.
    + Shorten your direct instruction time :: divide your content to smaller segments of about 10 to 20 minutes. Time yourself or ask a participant to give you a "time's up" signal.
    + Use short, quick review activities that engage all learners :: between lecture segments, use one-minute review activities.
    + Vary the review activities :: habituation sets in when the activity is repeated the same way, so slightly vary the strategies each time.
    + Use a Concept Map :: give each learner a concept map, and remind your learners to take notes on it.

*** Next Steps
    + Begin and end training with the focus on the learners, not on you :: step aside as learners participate in meaningful connections and conclussions.
    + Begin and end direct instruction with learner discussion :: engage learners with short, small group discussions before and after lecture segments.
    + Hand over some of the content to the learners to teach :: choose the easiest concept for participants to learn and set up an activity so you have them teach to each other.
    + Ask open-ended questions :: if a question has only one right answer, don't ask it
    + Pay attention to the message behind the message :: observe your own patterns of interaction to make sure they are inclusive and respectful.
    + Step aside and let them learn :: put them center-stage, and create ways for them to shine as they learn. Challenge yourself to find ways to teach them without always being the center of their attention and focus.

** CONCLUSSIONS
*** Bonus One-Minute Conclussion: Find That Phrase
    1. My greatest challenge is to step aside and talk less, so that learners can talk, interact, teach and learn from each other.
    2. Habituation describes the brain's hability to ignore anything repetitive or routine.
    3. Brain-friendly training uses positive emotions, multisensory estimulation, instructional variety and active participation.
    4. Instructor-led, content-centered, lecture-saturated training is brain-antagonistic.
    5. Television has conditioned us to getting our information in small "chunks" or segments of time.
    6. Brain-friendly training environments are informal, visually interesting, collaborative places to be

