hacked-notesearch: hacked-notesearch.c
	gcc -o hacked-notesearch hacked-notesearch.c -g -fno-stack-protector -z execstack -m32


main-of: main-of.c
	gcc -o main-of main-of.c -g -fno-stack-protector -z execstack -m32
